#ifndef USER_TASKS_USER_INTERFACE_TASK_H_
#define USER_TASKS_USER_INTERFACE_TASK_H_

#define USER_INTERFACE_TASK_PRIORITY     	10
#define USER_INTERFACE_TASK_STACK_SIZE	 	256


void TASK_RegisterUserInterfaceTask();

#endif /* USER_TASKS_USER_INTERFACE_TASK_H_ */
