#ifndef USER_TASKS_TEMPERATURE_CONTROL_TASK_H_
#define USER_TASKS_TEMPERATURE_CONTROL_TASK_H_

#define TEMPERATURE_CONTROLLER_TASK_PRIORITY     	10
#define TEMPERATURE_CONTROLLER_TASK_STACK_SIZE	 	512

#define TEMPERATURE_CONTROLLER_TASK_TICK_PERIOD_MS	100

void TASK_RegisterTemperatureControlTask(void);

#endif /* USER_TASKS_TEMPERATURE_CONTROL_TASK_H_ */
